### ISSUE TITLE
/vs 페이지에서 버그가 있습니다.

### ISSUE THREAD

**Issue by cgiosy** [shiftpsh/solvedac-plugin#11]
번호와 문제 이름을 모두 표시하도록 하였을 경우, 각각에 난이도 배지가 붙어 한 문제에 두 개가 붙게 되며, 각각의 문제에 요청을 하느라 속도가 매우 느려지게 됩니다.
또한 /user 페이지에선 배지가 생기지 않는 것으로 보아 원래는 표시되지 않아야 하는 것 같습니다.

**Comment by shiftpsh** [comment]
마침 저도 해당 버그를 오늘 인지했습니다. 다음 버전에서 표시되지 않도록 수정할 예정입니다.

**Comment by shiftpsh** [comment]
수정했습니다. 다음 릴리즈에서 확인하실 수 있습니다.
