### ISSUE TITLE
난이도 요청을 한 번에 하면 어떨까요?

### ISSUE THREAD

**Issue by Corea** [shiftpsh/solvedac-plugin#12]
solved.ac chrome extension 잘 쓰고 있는 유저입니다. 좋은 프로그램 만들어주셔서 고마워요.

그런데, 문제 목록을 열 때마다 `https://api.solved.ac/problem_level.php?id={id}`에 너무 많은 요청을 보내고 있는 것 같습니다. 난이도가 하나씩 달리는게 눈에 보이는데요. (이건 미국이라 그럴 수 있습니다) `https://api.solved.ac/problem_levels.php?ids={id1},{id2},...`와 같은 API를 만들어 동시에 여러 id를 핸들하면 어떨까요? latency가 큰 환경에서 더 좋은 UX를 보여줄 수 있을 것 같습니다.

**Comment by shiftpsh** [comment]
그렇게 하기보단 전체 난이도 정보를 요청하는 API를 만들어 일정 주기로 캐싱해두고자 생각하고 있었습니다. 의견 감사합니다!

**Comment by shiftpsh** [comment]
1.3에서 해결되었습니다.
