### ISSUE TITLE
난이도 의견 표시를 접을 수 있게 해주세요!

### ISSUE THREAD

**Issue by SDSkyKlouD** [shiftpsh/solvedac-plugin#14]
![image](https://user-images.githubusercontent.com/3761972/65295251-c00cf800-db9b-11e9-916e-8ec83ddd28f5.png)

최근에 난이도 의견까지 표시해주는 기능까지 구현하신 것 같은데, 난이도 제출자가 너무 많으면 한 화면을 다 채워버리는 것 같아요. 스크롤이 귀찮은 프로 PS러들을 위해 난이도 의견 영역을 줄여야 할 것 같다고 생각합니다.

다음 방법들 중 몇 가지로 해결할 수 있을 것 같아용.
  + 난이도 의견이 입력되지 않았다면 아예 표시하지 않기
  + 난이도 제출자의 닉네임 위에 마우스 호버링하면 난이도 의견을 툴팁같이 보여주기
  + 난이도 제출자 영역 자체를 아예 접어놓았다가 버튼을 누르면 펼쳐 보여주기
  + 난이도 의견 표시/비표시 여부를 확장의 설정으로 놓기 (난이도 의견이 스포일러가 될 수 있기도 하니까?)

**Comment by shiftpsh** [comment]
<img width="321" alt="스크린샷 2019-09-20 14 44 58" src="https://user-images.githubusercontent.com/4417431/65302307-c7d99600-dbb5-11e9-9b08-9a956a3ce325.png">
일단은은 이런 옵션이 제공되긴 합니다만 추가적으로 의견을 펼침/닫음 하거나 스크롤할 수 있게 해두겠습니다.

**Comment by shiftpsh** [comment]
<img width="1180" alt="스크린샷 2019-09-20 15 08 42" src="https://user-images.githubusercontent.com/4417431/65303284-8dbdc380-dbb8-11e9-80fc-5d6ad19029b0.png">
스크롤 가능하게 바꿨습니다.
