### ISSUE TITLE
404 에러 해결 해주세요.

### ISSUE THREAD

**Issue by sbrus1213** [shiftpsh/solvedac-plugin#18]
메인화면에서 로고 이미지 속에 있는 로그인 버튼 눌러서 로그인 할 때, 404에러 페이지로 이동합니다. (로그인은 정상적으로 됩니다.)
페이지 상단 로그인 버튼을 눌렀을 때는 이상없습니다.

**Comment by shiftpsh** [comment]
답변이 늦어서 죄송합니다. 며칠째 고치려고 노력중이었는데 원인을 찾지 못하고 있습니다.
그리고 사이트 관련 이슈는 메일 혹은 슬랙에서 부탁드립니다. 플러그인 이슈에는 플러그인 관련 이슈만 부탁드립니다.
