### ISSUE TITLE
Firefox add-on 을 더 이상 사용할 수 없습니다

### ISSUE THREAD

**Issue by yujingaya** [shiftpsh/solvedac-plugin#21]
[홈페이지](https://solved.ac/)와 [README](https://github.com/shiftpsh/solvedac-plugin/blob/master/README.md)에서 제공하는 [Firefox add-on 링크](https://addons.mozilla.org/ko/firefox/addon/solved-ac/)에 접속하니

- 개발자가 항목을 제거하였습니다. 개발자들은 일반적으로 부가 기능이나 테마를 더이상 지원하지 않거나 대체하기 위해서 이렇게 합니다.
- Mozilla가 제거한 것입니다. 이는 부가 기능이나 테마의 검토 과정에서 문제가 발생했거나, addons.mozilla.org의 이용 약관을 위반한 경우입니다. 개발자는 문제를 해결하고 부가 기능을 다시 내려받을 수 있도록 할 수 있습니다.

라고 안내하고 있습니다.

**Comment by shiftpsh** [comment]
확인되지 않은 버전의 3rd party 라이브러리를 사용한 게 원인이 되어 Mozilla 측에서 게시중단했습니다. 귀국한 지 얼마 안 되어 당장은 힘들지만 최대한 빨리 고쳐서 다시 게시하겠습니다

**Comment by shiftpsh** [comment]
일단 재게시했습니다.
