### ISSUE TITLE
태그로 문제를 볼 때 푼 사람이 많은 순으로 정렬할 수 있었으면 좋겠습니다

### ISSUE THREAD

**Issue by computerphilosopher** [shiftpsh/solvedac-plugin#25]
현재는 난이도 순 정렬이 되어있는데 푼 사람이 많은 순의 정렬도 가능하면 좋겠습니다.

**Comment by shiftpsh** [comment]
정렬 옵션을 다양화할 계획은 있습니다만 현재는 바빠서 못 하고 있었습니다. 의견 감사합니다!

**Comment by shiftpsh** [comment]
올해 초에 기능이 추가된 기능이었습니다만, 레포가 archived 되어 있었어서 이슈를 늦게 닫습니다.
