### ISSUE TITLE
[계정본인확인과정] 15802번 문제는 제출 버튼이없습니다.

### ISSUE THREAD

**Issue by OhSaehong** [shiftpsh/solvedac-plugin#26]
15802 타노스 문제는 19년 11월 21일 오후 9시 43분 기준으로 채점준비중인 상태라,

제출을 할수 없으며, 이에 따른 링크 공유도 불가합니다.

조치 부탁드려요

**Comment by shiftpsh** [comment]
17113번으로 수정했습니다.
