### ISSUE TITLE
제출 화면에서 난이도 배지가 엉뚱한 곳에 붙어 있습니다.

### ISSUE THREAD

**Issue by sohnryang** [shiftpsh/solvedac-plugin#3]
![image](https://user-images.githubusercontent.com/15506585/61729830-14ba0f80-adb3-11e9-93f7-508b0cccdeb0.png)

그림에서 보듯 제출 화면에서 문제 번호 옆에 난이도 배지가 없어야 하는데 있습니다.

**Comment by shiftpsh** [comment]
<img width="274" alt="스크린샷 2019-07-27 01 49 33" src="https://user-images.githubusercontent.com/4417431/61967615-cf931900-b010-11e9-98bd-3eb19e9606b1.png">

1.1.2에서는 조금 더 자연스러운 위치에 붙어 있도록 수정했습니다.
