### ISSUE TITLE
Firefox Extension

### ISSUE THREAD

**Issue by sohnryang** [shiftpsh/solvedac-plugin#8]
코드의 수정 없이, 크롬 확장을 파이어폭스에서 [사용할 수 있습니다.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension)
solved.ac extension도 제가 테스트해본 결과 제대로 실행되는 것 같습니다. (티어가 딸려서 난이도 투표는 테스트를 못해봤습니다.)

README에 설치 방법을 올리고,  빌드하고 Sign한 Extension 파일을 올리면 좋을 것 같습니다.

**Comment by shiftpsh** [comment]
늦게 답장드려 죄송합니다. 로그인 부분에서 chrome storage API를 사용하고 있는데 이 부분이 문제가 되지 않을까요? 일단 제 환경에서 테스트해 보고 게시하겠습니다.

**Comment by sohnryang** [comment]
음 적어도 제 파폭에서는 돌아가네요.

**Comment by shiftpsh** [comment]
로그인/로그아웃이 잘 되나요? 그것만 확인해 주시면 내일 바로 올리겠습니다.

**Comment by sohnryang** [comment]
> 로그인/로그아웃이 잘 되나요? 그것만 확인해 주시면 내일 바로 올리겠습니다.

네 됩니다. 난이도 투표는 돌아갈지 잘 모르겠네요.. (언제 `Platinum V` 가지 :cry:)

**Comment by cgiosy** [comment]
파이어폭스 69에서 확인해본 결과 로그인, 로그아웃을 비롯한 모든 기능 정상 작동합니다. [확장기능 호환성 테스트](https://www.extensiontest.com/)도 통과한 것을 보면 별다른 수정 없이 그대로 배포해도 될 것 같습니다.

**Comment by shiftpsh** [comment]
방금 로컬에서 테스트해봤고 문제없이 동작하는 것을 확인했습니다. 이슈 몇 개 고치고 다음 버전부터는 Firefox에도 릴리즈하겠습니다. 감사합니다!

**Comment by sohnryang** [comment]
감사합니다!
