### ISSUE TITLE
새로운 문제의 난이도 표시

### ISSUE THREAD

**Issue by sohnryang** [shiftpsh/solvedac-plugin#9]
solved.ac의 백엔드가 정확히 어떤지는 모르겠지만, 문제 난이도 정보도 30분 주기로 업데이트되는 것이라고 추측하겠습니다.

> BOJ 서버 부하를 최소화하기 위해 경험치, 문제 해결 여부는 매시 0분, 30분 즈음에 업데이트됩니다.

BOJ에 새로운 문제가 등록되었지만, 아직 서버에 난이도 정보가 저장되지 않은 경우, 난이도 배지가 아예 뜨지 않습니다. 이러한 경우에도 Unranked 배지를 보여주거나, solved.ac 서버에 아직 올라가지 않았다는 사실을 알려주기 위해 Unlisted 등의 배지를 보여주는 것이 좋을 것 같습니다.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/15506585/62688201-5a0d4c80-ba03-11e9-9341-e51bce7e8cc6.png">

**Comment by shiftpsh** [comment]
문제 데이터베이스는 매일 새벽 6시에 업데이트됩니다. Unlisted 혹은 관련 기능 만들어보도록 하겠습니다.

**Comment by shiftpsh** [comment]
v1.1.5에서 수정되었습니다. 감사합니다!
<img width="638" alt="스크린샷 2019-08-21 23 26 56" src="https://user-images.githubusercontent.com/4417431/63440742-59e16800-c46b-11e9-9379-1874f0395f2e.png">
<img width="303" alt="스크린샷 2019-08-21 23 27 08" src="https://user-images.githubusercontent.com/4417431/63440751-5b129500-c46b-11e9-8868-0868107363fc.png">
